"""
src/reporting/markdown_writer.py

Assembles the final Markdown PADER report from generated sections.

Guarantees:
  - ALL 8 sections are always written, even if FLAGGED.
  - Generated content always appears BEFORE validation notes.
  - Validation notes use structured CONTRADICTED / UNVERIFIED labels.
  - Review Status Summary accurately reflects per-section status and issue count.
  - A FLAGGED section always contains at least one issue description.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from src.config.report_config import SECTION_ORDER
from src.models.schemas import ReportSection, ReviewStatus

logger = logging.getLogger(__name__)

REPORT_VERSION = "0.1.0"


class MarkdownWriter:
    """
    Assembles and writes the final Markdown PADER report.

    Usage:
        writer = MarkdownWriter(output_path="reports/draft_report.md")
        writer.write(sections, metadata, case_listing_path="evidence/case_listing.json")
    """

    def __init__(self, output_path: str | Path = "reports/report_output.md") -> None:
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def write(
        self,
        sections: list[ReportSection],
        metadata: dict,
        case_listing_path: str | Path = "evidence/case_listing.json",
        validation_result=None,
    ) -> Path:
        """
        Assemble and write the full PADER report.

        Args:
            sections:          List of generated ReportSection objects.
            metadata:          metadata.json dict from evidence store.
            case_listing_path: Path to case_listing.json for deterministic table.
            validation_result: OutputValidationResult (optional, for summary).

        Returns:
            Path to the written report file.
        """
        lines: list[str] = []

        # --- Report header ---
        lines += self._build_header(metadata)

        # --- Sections (in defined order; missing sections are flagged, never silently dropped) ---
        section_map = {s.section_name: s for s in sections}
        for i, section_name in enumerate(SECTION_ORDER, start=1):
            section = section_map.get(section_name)
            if section is None:
                logger.error(
                    "REQUIRED section '%s' is MISSING from generated sections.", section_name
                )
                lines += self._build_missing_section(i, section_name)
            else:
                lines += self._build_section(i, section, case_listing_path)

        # --- Validation summary ---
        lines += self._build_validation_summary(sections, validation_result)

        # --- Footer ---
        lines += self._build_footer()

        # Write to file
        report_text = "\n".join(lines)
        self.output_path.write_text(report_text, encoding="utf-8")
        size_kb = self.output_path.stat().st_size / 1024
        logger.info("Report written: %s (%.1f KB)", self.output_path, size_kb)
        return self.output_path

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------

    def _build_header(self, metadata: dict) -> list[str]:
        period_start = metadata.get("reporting_period_start", "unknown")
        period_end   = metadata.get("reporting_period_end",   "unknown")
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        total_cases  = metadata.get("total_cases") or (
            metadata.get("canonical_data_model", {}).get("unique_cases", "unknown")
        )
        total_cases_str = f"{total_cases:,}" if isinstance(total_cases, int) else str(total_cases)

        return [
            "# PADER Report — Bisoprolol Adverse Drug Experience",
            "",
            f"**Product:** Bisoprolol  ",
            f"**Reporting Period:** {period_start} to {period_end}  ",
            f"**Report Generated:** {generated_at}  ",
            f"**Report Version:** {REPORT_VERSION}  ",
            f"**Analysis Version:** {metadata.get('analysis_version', 'unknown')}  ",
            f"**Source File:** {metadata.get('source_file', 'unknown')}  ",
            f"**Total Cases:** {total_cases_str}  ",
            "",
            "> **IMPORTANT — HUMAN REVIEW REQUIRED**  ",
            "> This report was generated by an automated AI pipeline. All sections require "
            "review and approval by a qualified pharmacovigilance professional "
            "before submission or distribution.  ",
            "> Evidence-based numbers were computed deterministically from the ICSR dataset. "
            "Narrative text was generated by an LLM and is subject to validation notes in each section.  ",
            "",
            "---",
            "",
        ]

    # ------------------------------------------------------------------
    # Missing section placeholder
    # ------------------------------------------------------------------

    @staticmethod
    def _build_missing_section(number: int, section_name: str) -> list[str]:
        return [
            f"## {number}. {section_name}",
            "",
            "*Review Status: **MISSING***  ",
            "",
            "> **[ERROR]** This required section was not generated. "
            "The report cannot be approved until this section is present.",
            "",
            "---",
            "",
        ]

    # ------------------------------------------------------------------
    # Section rendering
    # ------------------------------------------------------------------

    def _build_section(
        self,
        number: int,
        section: ReportSection,
        case_listing_path: str | Path,
    ) -> list[str]:
        status_label = section.review_status.value.upper()
        lines = [
            f"## {number}. {section.section_name}",
            "",
            f"*Review Status: **{status_label}***  ",
            "",
        ]

        # ── Generated content ALWAYS comes first ─────────────────────────
        if section.generated_text.strip():
            lines += [section.generated_text.strip(), ""]
        else:
            lines += ["> *[No content generated for this section.]*", ""]

        # ── Deterministic case table (appended after intro text) ──────────
        if section.section_name == "Case Index / Listing":
            lines += self._build_case_table(case_listing_path)

        # ── Validation notes (collapsible) ────────────────────────────────
        if section.validation_notes:
            lines += self._build_validation_block(section)

        lines += ["---", ""]
        return lines

    @staticmethod
    def _build_validation_block(section: ReportSection) -> list[str]:
        """Format validation notes in a collapsible block with structured labels."""
        lines = [
            "<details>",
            "<summary>Automated Validation Notes</summary>",
            "",
        ]
        contradicted = [n for n in section.validation_notes if "[CONTRADICTED]" in n]
        unverified   = [n for n in section.validation_notes if "[UNVERIFIED]" in n]
        info         = [n for n in section.validation_notes
                        if "[CONTRADICTED]" not in n and "[UNVERIFIED]" not in n]

        if contradicted:
            lines.append("**CONTRADICTED claims (require correction):**")
            lines.append("")
            for note in contradicted:
                # Each note may be multiline — emit each line as a bullet
                for sub_line in note.split("  \n"):
                    sub_line = sub_line.strip()
                    if sub_line:
                        lines.append(f"- {sub_line}")
            lines.append("")

        if unverified:
            lines.append("**UNVERIFIED claims (human review required):**")
            lines.append("")
            for note in unverified:
                lines.append(f"- {note}")
            lines.append("")

        if info:
            for note in info:
                lines.append(f"- {note}")
            lines.append("")

        lines += ["</details>", ""]
        return lines

    # ------------------------------------------------------------------
    # Deterministic case table
    # ------------------------------------------------------------------

    def _build_case_table(self, case_listing_path: str | Path) -> list[str]:
        """
        Render the full case index as a Markdown table from case_listing.json.
        This section is NEVER generated by the LLM.
        """
        path = Path(case_listing_path)
        if not path.exists():
            return [
                "",
                "*Case listing not available — evidence/case_listing.json not found.*",
                "",
            ]

        with open(path, encoding="utf-8") as f:
            listing = json.load(f)

        lines = [
            "",
            f"*The following table lists all {len(listing)} cases in the dataset. "
            "Generated deterministically from evidence/case_listing.json.*",
            "",
            "| Case ID | Received | Country | Sex | Age Group | Serious | Expedited | Reactions | Outcomes |",
            "|---------|----------|---------|-----|-----------|---------|-----------|-----------|----------|",
        ]

        for case in listing:
            rxns_full = "; ".join(case.get("reactions", []))
            reactions_str = rxns_full[:80] + ("..." if len(rxns_full) > 80 else "")
            outcomes_str  = "; ".join(case.get("outcomes", []))

            lines.append(
                f"| {case['safetyreportid']} "
                f"| {case['receivedate']} "
                f"| {case['country']} "
                f"| {case['sex']} "
                f"| {case['age_group']} "
                f"| {'Yes' if case['is_serious'] else 'No'} "
                f"| {'Yes' if case['is_expedited'] else 'No'} "
                f"| {reactions_str} "
                f"| {outcomes_str} |"
            )

        lines += [""]
        return lines

    # ------------------------------------------------------------------
    # Validation summary
    # ------------------------------------------------------------------

    def _build_validation_summary(
        self,
        sections: list[ReportSection],
        validation_result=None,
    ) -> list[str]:
        lines = [
            "## Validation Summary",
            "",
            "| # | Section | Status | Contradicted | Unverified |",
            "|---|---------|--------|-------------|------------|",
        ]
        for i, section in enumerate(sections, start=1):
            contradicted_count = sum(
                1 for n in section.validation_notes if "[CONTRADICTED]" in n
            )
            unverified_count = sum(
                1 for n in section.validation_notes if "[UNVERIFIED]" in n
            )
            status_label = section.review_status.value.upper()
            lines.append(
                f"| {i} | {section.section_name} "
                f"| {status_label} "
                f"| {contradicted_count} "
                f"| {unverified_count} |"
            )

        # Overall generation status
        gen_status = "COMPLETE"
        if any("[GENERATION ERROR]" in s.generated_text for s in sections):
            gen_status = "INCOMPLETE — LLM generation failed for one or more sections"

        lines += [
            "",
            f"**Generation Status:** {gen_status}  ",
            "",
            "---",
            "",
        ]
        return lines

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------

    @staticmethod
    def _build_footer() -> list[str]:
        return [
            "## Generation Notes",
            "",
            "- **Evidence store:** All quantitative facts were computed deterministically "
            "by the analysis engine from the supplied ICSR dataset.",
            "- **LLM role:** The LLM generated narrative text only. It did not compute "
            "any numbers, perform seriousness assessments, or determine expectedness.",
            "- **Validation:** Each narrative section was checked by the automated output "
            "validator for capability violations, safety conclusions, and numeric accuracy.",
            "- **Human review:** All sections require review by a qualified pharmacovigilance "
            "professional before use.",
            "- **Limitations:** SOC analysis, expectedness assessment, history of actions, "
            "and cumulative counts are not available for this dataset.",
            "",
        ]
